language: cpp
dist: bionic
compiler: gcc

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: ['g++-9', 'libboost-all-dev']

install:
  - export CXX="g++-9" CC="gcc-9"
  - mkdir -p build && cd build
  - cmake ..
  - VERBOSE=1 make -j4
  - cd ..

script:
  - cd build
  - ctest -V
