language: cpp
dist: xenial
compiler: gcc

before_install:
  - sudo apt-get install -y libboost-all-dev 

install:
  - mkdir -p build && cd build
  - cmake ..
  - VERBOSE=1 make -j4
  - cd ..

script:
  - cd build
  - ctest -V
