language: cpp

compiler: gcc

before_install:
  - git submodule update --init --recursive

install:
  - export CXX=g++-4.8
  - wget https://github.com/Viq111/travis-container-packets/releases/download/boost-1.57.0/boost.tar.bz2 # Get boost
  - tar -xjf boost.tar.bz2
  - rm boost.tar.bz2
  - export BOOST_ROOT=$(pwd)/boost
  - mkdir build; cd build
  - cmake ..
  - make
  - cd ..

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-4.8
      - g++-4.8
      - zlib1g-dev
      - libbz2-dev

script:
  - cd build
  - ctest -V
